# Generated by Django 5.2.7 on 2025-10-17 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('volume_type', models.CharField(choices=[('single', 'Единичный'), ('multiple', 'Множественный')], max_length=10, verbose_name='Тип объема')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Документ')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('status', models.CharField(choices=[('создан', 'Создан'), ('обрабатывается', 'Обрабатывается'), ('собирается', 'Собирается'), ('доставляется', 'Доставляется'), ('готов', 'Готов')], default='создан', max_length=20, verbose_name='Статус')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ready_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата готовности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_date'],
            },
        ),
    ]
